---
name: default
kind: pipeline
type: docker

pipeline:
  buildsite:
    image: klakegg/hugo:0.75.1-alpine
  deploy:
    image: drillster/drone-rsync
    hosts: [ "murakumo.tarxvf.tech" ]
    user: wwwdeploy
    port: 15558
    source: public/
    target: /srv/http/rflabs.tarxvf.tech/
    delete: true
    secrets: [plugin_key]
    when:
      branch:
      - master

