---
name: default
kind: pipeline
type: docker

pipeline:
  buildimage:
    context: .
  buildsite:
    command: hugo --cleanDestinationDir --verbose
  deploy:
    image: drillster/drone-rsync
    hosts: [ "murakumo.tarxvf.tech" ]
    user: wwwdeploy
    port: 15558
    source: public/
    target: /var/www/rflabs.tarxvf.tech/
    delete: true
    secrets: [plugin_key]
    when:
      branch:
      - master

